# Example override file. Copy as docker-compose.override.yml and edit as needed

services:
  nginx:
    ports:
      - "81:80"
  web:
    env_file:
      - ./config/prod.env
      - ./config/wger-local.env # Only add the variables that you have changed

  celery_worker:
    env_file:
      - ./config/prod.env
      - ./config/wger-local.env

  celery_beat:
    env_file:
      - ./config/prod.env
      - ./config/wger-local.env

  celery_flower:
    image: wger/server:latest
    container_name: wger_celery_flower
    command: /start-flower
    env_file:
      - ./config/prod.env
    ports:
      - "5555:5555"
    healthcheck:
      test: wget --no-verbose --tries=1 http://localhost:5555/healthcheck
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      celery_worker:
        condition: service_healthy
